config/routes.rb
RailsNote::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sessions" => "sessions#new"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"
  resources :users
  resources :sessions

  

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :notebook
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  belongs_to :user
  has_many :notes
  validate :title, presence: true, length: { minimun: 1 }
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password

	has_many :notebooks
	validates_uniqueness_of :email
	validates_length_of :email, :within => 5..50
	validates_format_of :email, :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i, :multiline => true

	validates_presence_of :password, :on => :create
	validates_confirmation_of :password

	def encrypt_password
		if password.present?
			self.password_hash = Digest::SHA1.hexdigest(password)
		end
	end

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == Digest::SHA1.hexdigest(password)
			user
		else
			nil
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  protected
	  def current_user
	  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end

	  def authenticate
	  	current_user.is_a? User || access_denied
	  end

	  def access_denied
	  	redirect_to log_in_path, notice: "Please log in to continue"
	  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'log-layout'
  
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'log-layout'

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsNote</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash#{name}" %>
		<% end %>

		<div id="user_nav">
			<% if current_user %>
				Logged in as <%= current_user.email %>
				<%=  link_to "Log out", log_out_path %>
			<% else %>
				<%= link_to "Sign up", sign_up_path %> or 
				<%= link_to "Log in", log_in_path %>	
			<% end %>
		</div>

		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/log-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsNote</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "sessions", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-offset-4 col-md-4">
			<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash#{name}", class:"alert alert-danger text-center msg-alert" %>
			<% end %>
			</div>
		</div>

		<% if @user && @user.errors.any? %>
			<div class="row">
			<div class="col-md-offset-4 col-md-4">
					<% for message in @user.errors.full_messages %>
						<%= content_tag :div, message, class:"alert alert-danger text-center msg-alert" %>
					<% end %>
			</div>
			</div>
		<% end %>

		
		<div class="row" id="container-login">
			<div class="col-lg-offset-4 col-lg-4 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6 col-xs-offset-1 col-xs-10">
				<figure class="text-center">

					<%= image_tag "railsnote.png", class:"img " %>
				</figure>

				<%= yield %>

			</div>
		</div>
		<footer class="text-center">
			<span class="label-form">DevAngeles 2014</span>
		</footer>
	</div>
</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	
	<h1 class="text-center title-login">Sign up</h1>

	<div class="well">
		<p>
			<%= f.label :email, class:"label-form" %><br/>
			<%= f.text_field :email, class:'form-control' %>
		</p>
		<p>
			<%= f.label :password, class:"label-form"  %><br/>
			<%= f.password_field :password, class:"form-control" %>
		</p>
		<p>
			<%= f.label :password_confirmation, class:"label-form" %><br/>
			<%= f.password_field :password_confirmation, class:"form-control" %>
		</p>
		<div class="text-center">
			<%= f.submit class:"btn btn-success btn-login" %>
		</div>
		
	</div>
	
<% end %>